
CREATE TABLE Usuarios (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    UserName NVARCHAR(50) NOT NULL UNIQUE,
    SenhaHash NVARCHAR(255) NOT NULL
);

CREATE TABLE Enderecos (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Cep NVARCHAR(8) NOT NULL,
    Logradouro NVARCHAR(200) NOT NULL,
    Complemento NVARCHAR(200) NULL,
    Bairro NVARCHAR(100) NOT NULL,
    Cidade NVARCHAR(100) NOT NULL,
    Uf NVARCHAR(2) NOT NULL,
    Numero NVARCHAR(20) NOT NULL,
    UsuarioId INT NOT NULL,
    CONSTRAINT FK_Enderecos_Usuarios FOREIGN KEY (UsuarioId)
        REFERENCES Usuarios(Id)
        ON DELETE CASCADE
);